### ISSUE TITLE
Add cap and resistor

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#2]
Add (1) cap and (1) terminating resistor to the PCB inside the ear piece. 
See [Wiring Diagram_RIC Hearing Aid_Rev-B.pdf](https://github.com/Tympan/Earpiece_BTE-RIC_V1/blob/master/Electrical%20Design/Schematics_PDF/Wiring%20Diagram_RIC%20Hearing%20Aid_Rev-B.pdf)

**Comment by biomurph** [comment]
On it!

**Comment by eyuan-creare** [comment]
@biomurph  Sorry, these components go on the PCB not the flex.  I forgot.
