### ISSUE TITLE
Verify flex thickness where the mics are mounted

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#3]
I need to allow the proper gap between the face of the mic and the enclosure wall.  What is the thickness of the flex where the mics are mounted?

**Comment by biomurph** [comment]
We get to define the thickness of the flex pcb. you have it spec'd out at 0.12+/-0.03 and so that's what I'm shooting for. Does that dimension still hold?

**Comment by eyuan-creare** [comment]
Yes.  works for me.
