### ISSUE TITLE
Review BTE Rigid Board Design

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#4]
- [x] Check board edges
- [x] Check routing and schematic: Speaker polarity was wrong.  Created issue #5 

Otherwise ready to go!

**Comment by eyuan-creare** [comment]
Board edges line up great.
![image](https://user-images.githubusercontent.com/42774675/65326826-5501f800-db80-11e9-8e65-e57b7475311c.png)

Pads for flying leads were shifted.  I corrected them in SW and will revise my drawing.  Also added a missing dimension in my SW drawing to set this pad location.
![image](https://user-images.githubusercontent.com/42774675/65327021-cd68b900-db80-11e9-8c64-8a996af0e9bb.png)

**Comment by eyuan-creare** [comment]
Pads for FPC connector were shifted a bit, which makes sense--they needed more room for the board margin. 
![image](https://user-images.githubusercontent.com/42774675/65328428-4fa6ac80-db84-11e9-9d4f-e94e0886c235.png)
 I revised the part in SW an updated the drawing.  Outlines now match
![image](https://user-images.githubusercontent.com/42774675/65331082-08231f00-db8a-11e9-88ed-c5b5ab3c6dbe.png)

**Comment by eyuan-creare** [comment]
Pin order of the body cable was different than in my wiring diagram.  Eric will correct the wiring diagram.
![image](https://user-images.githubusercontent.com/42774675/65334254-0fe5c200-db90-11e9-952d-a2cd01ec02e9.png)

![image](https://user-images.githubusercontent.com/42774675/65334236-03fa0000-db90-11e9-83ca-16bb7773eae8.png)

**Comment by eyuan-creare** [comment]
Routing of wires is correct (other than speaker - and speaker + was swapped).  See issue #5

**Comment by eyuan-creare** [comment]
Should there be a BOM and a pick and place table?  Created issue #7

**Comment by biomurph** [comment]
I had to swap the wire order to ease routing.
Are you are able to make the changes on your end to the slight offset of my layout?

**Comment by eyuan-creare** [comment]
Review complete

**Comment by eyuan-creare** [comment]
Yes, corrected it on my end (Issue #9)

@biomurph  But note that you will need to swap the speaker labels (but preserve the speaker routes)
