### ISSUE TITLE
BTE Rigid PCB: Swap labels for speaker polarity

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#5]
The speaker polarity is switched.  Change pin#4 to (-) and pin#3 to (+)
![image](https://user-images.githubusercontent.com/42774675/65332664-1cb4e680-db8d-11e9-91b6-38966837761e.png)

![image](https://user-images.githubusercontent.com/42774675/65333582-c648a780-db8e-11e9-954b-80d3faf6947f.png)

**Comment by biomurph** [comment]
Oh dang. I stared at that one too long.

**Comment by biomurph** [comment]
At least it won't require any re-routing, just a net swap.

**Comment by biomurph** [comment]
and, done
