### ISSUE TITLE
Rigid PCB: Label color of body cable leads

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#6]
Should we label the color of the body cable leads on the schematic?  Just for reference.  

Would the PCB house be willing to solder these leads to the PCB?  Would they have better tools for that than us?

**Comment by biomurph** [comment]
Yes, assigning color to the connections on the schematic is a good idea. 

I will be doing the assembly in-house, with my badass skills (tools)!

**Comment by biomurph** [comment]
Done
