### ISSUE TITLE
Review BTE Flex design

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Earpiece_BTE-RIC_V1#8]
Logging our past communication (Joel + Eric) and adding a few more checks
- [x] Outline
- [x] Distance between mic holes
- [x] Tail length: Note that the tail from Joel's flex outline is a little longer.  That’s because in Solidworks I modeled the minimum tail length.  You were right to make the tail a little longer.  Thank you for paying attention to detail. No change needed
- [X] Routing
- [X] Check pin order
- [X] Check that pads are located on the correct side (front vs back)

Looks good!

**Comment by eyuan-creare** [comment]
* Pads for mic are located correctly on the back side
* Pin order of the flex tail matches the pin order of the FPC connector

__Views of the right side of the PCB__
![image](https://user-images.githubusercontent.com/42774675/65335494-84b9fb80-db92-11e9-9944-857670a6821e.png)

![image](https://user-images.githubusercontent.com/42774675/65335701-e7ab9280-db92-11e9-85f4-88c258a4a63a.png)

**Comment by biomurph** [comment]
- Checking pin order of the tail

Yes, please do. I stared at that for a long time too!
